name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t taxonomy_docker_image .
          docker docker_image taxonomy_docker_image:latest ${{ steps.login-ecr.outputs.registry }}:docker_image
          docker push ${{ steps.login-ecr.outputs.registry }}:docker_image
        env:
          AWS_REGION: ap-south-1
          AWS_ACCOUNT_ID: ${{ secrets.098990370730 }}
